create or replace TABLE FDB_MNG_TRANSFORM_LYR.SCH_MNG_TL.METRICS_Devops_CICD (
	MODEL_NAME VARCHAR(16777216) NOT NULL,
	MEAN_ABSOLUTE_ERROR_SCORE FLOAT,
	MEAN_SQUARED_ERROR_SCORE FLOAT,
	R2_SCORE FLOAT
)