---
on:
  push:
    paths:
      - 'dbscripts/**'
  pull_request:
    paths:
      - 'dbscripts/**'

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

jobs:
  RunChecks:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Terraform version
        run: echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> "$GITHUB_ENV"
        id: set-terraform-version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Authenticate against production account
        uses: "aws-actions/configure-aws-credentials@v2"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}     

      - name: Terraform init
        id: terraform-init
        run: terraform init

      - name: Terraform format
        id: terraform-fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: terraform-validate
        run: terraform validate

      - name: Terraform plan
        id: terraform-plan
        run: terraform plan

      - name: Terraform apply
        id: terraform-apply
        run: terraform apply -auto-approve