name: Snowflake Terraform Demo Workflow

on:
  push:
    branches:
    - main

jobs:
  snowflake-terraform-demo:
    name: Snowflake Terraform Demo Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format Check
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Set Formatting Output
      if: failure()
      run: echo "terraform_fmt_check=failed" >> $GITHUB_ENV
      # Update to use Environment Files
      run: |
        echo "terraform_fmt_check=failed" >> $GITHUB_ENV

    - name: Terraform Init
      id: init
      run: terraform -chdir=./Terraform-Snowflake-Github-Actions init

    - name: Terraform Validate
      id: validate
      run: terraform -chdir=./Terraform-Snowflake-Github-Actions validate

    - name: Terraform Plan
      run: terraform -chdir=./Terraform-Snowflake-Github-Actions plan -out=tfplan -parallelism=20 -var="snowflake_account=${{ secrets.SNOWFLAKE_ACCOUNT }}" -var="snowflake_user=${{ secrets.SNOWFLAKE_USER }}" -var="snowflake_password=${{ secrets.SNOWFLAKE_PASSWORD }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform -chdir=./Terraform-Snowflake-Github-Actions apply -auto-approve tfplan
